#!/bin/zsh

alias ack-grep='ack'
alias ls=' ls --color=auto'
alias ll=' ls -al'
alias cd=' cd'
alias diff=colordiff

alias gst='git status -s'

alias root='cd $(git root)'

alias screen-conf='sudo $HOME/.profile/bin/screen-config'

alias print-colors='for i in {0..255} ; do printf "\x1b[38;5;${i}m ${i}"; done'

# NSS Configuration
alias gcert='certutil -d sql:$HOME/.pki/nssdb'

# This breaks shit that depends on ssh
#alias ssh='eval $(/usr/bin/keychain --eval -Q --quiet id_rsa cuda) && ssh'

alias homeshick="source $HOME/.homesick/repos/homeshick/bin/homeshick.sh"

alias pdb='XDEBUG_CONFIG="idekey=siler" php -d xdebug.remote_enable=1'
alias google-chrome="google-chrome-stable"
